"""Remove Admin.authenticated column.

Revision ID: 0cf249bb168b
Revises: 7a2a4fa5ae3e
Create Date: 2021-03-04 18:20:06.685886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf249bb168b'
down_revision = '7a2a4fa5ae3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'authenticated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('authenticated', sa.BOOLEAN(), server_default='False', autoincrement=False, nullable=False))
    # ### end Alembic commands ###
