"""Rename Admin.email column to Admin.username.

Revision ID: 3e5e570b1193
Revises: 0cf249bb168b
Create Date: 2021-03-04 18:41:13.352745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e5e570b1193'
down_revision = '0cf249bb168b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin', "email", nullable=False, new_column_name="username")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin', "username", nullable=False, new_column_name="email")
    # ### end Alembic commands ###
