"""Posts.date object is timezone aware datetime object

Revision ID: b084cbb1c085
Revises: 0fa07cf511f7
Create Date: 2021-03-08 14:55:40.087644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b084cbb1c085'
down_revision = '3e5e570b1193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
